name: Build GKI

on:
  workflow_call:
    inputs:
      TODO:
        type: string
        default: "kernel"
      VARIANT:
        type: string
        default: "KSUS"
      KERNELNAME:
        type: string
        default: "Focalors"
      KERNELBRANCH:
        type: string
        default: "test"
      LAST_BUILD:
        type: string
        default: "false"

  workflow_dispatch:
    inputs:
      TODO:
        description: To do
        default: "kernel"
        type: choice
        options:
          - "kernel"
          - "defconfig"
      VARIANT:
        description: kernel variants
        default: "KSUS"
        type: choice
        options:
          - "VNL"
          - "KSU"
          - "KSUS"
      KERNELBRANCH:
        description: "Kernel source branch"
        required: true
        default: "test"
        type: choice
        options:
          - lts
          - test
          - staging
          - android_kernel_common-5.10
          - android12-5.10-staging
      KERNELNAME:
        description: kernel Name
        default: "Focalors"
        type: string

env:
  MAN_DISABLE: true
  DEBIAN_FRONTEND: noninteractive
  BASE_NAME: Altair
  
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

  VARIANT: ${{ inputs.VARIANT || 'KSUS' }}
  KERNELNAME: ${{ inputs.KERNELNAME || 'Focalors' }}
  KERNELBRANCH: ${{ inputs.KERNELBRANCH || 'test' }}
  TODO: ${{ inputs.TODO || 'kernel' }}
  LAST_BUILD: ${{ inputs.LAST_BUILD || 'false' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Determine Build Status
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "STATUS=BETA" >> $GITHUB_ENV
          else
            echo "STATUS=RELEASE" >> $GITHUB_ENV
          fi

      - name: "Setup Swap 20GB"
        uses:pierotofy/set-swap-space@master
        with:
          swap-size-gb: 20

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex libssl-dev libelf-dev dwarves cpio aria2 zip unzip
          pip install lxml

      - name: Run Build Script
        run: |
          chmod +x *.sh py/*.py
          ./build.sh

      - name: Upload AnyKernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BASE_NAME }}-${{ github.run_number }}
          path: ./*.zip
