name: Release Build
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        variant:
          - { name: "VNL", VARIANT: "VNL", LAST_BUILD: "false" }
          - { name: "KSU", VARIANT: "KSU", LAST_BUILD: "false" }
          - { name: "KSUS", VARIANT: "KSUS", LAST_BUILD: "true" }
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      VARIANT: ${{ matrix.variant.VARIANT }}
      LAST_BUILD: ${{ matrix.variant.LAST_BUILD }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_files
      - name: Flatten Artifacts
        run: |
          mkdir -p final_release
          find release_files -name "*.zip" -exec cp {} final_release/ \;
      - name: Create Release
        run: |
          gh release create "Build-${{ github.run_number }}" \
            --title "Anisphia Build ${{ github.run_number }}" \
            --notes-file "release.md" \
            final_release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
