name: Release Build
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        variant:
          - { name: "VNL", VARIANT: "VNL", LAST_BUILD: "false" }
          - { name: "KSU", VARIANT: "KSU", LAST_BUILD: "false" }
          - { name: "KSUS", VARIANT: "KSUS", LAST_BUILD: "true" }
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      VARIANT: ${{ matrix.variant.VARIANT }}
      LAST_BUILD: ${{ matrix.variant.LAST_BUILD }}

  release:
    permissions:
      contents: write

    name: Create Unified Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_files

      - name: Generate release tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            RELEASE_TAG="5.10"

            echo "Release tag: $RELEASE_TAG"
            echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Upload All Builds to release repo
        run: |
          gh release create "$RELEASE_TAG" \
            --repo "$RELEASE_REPO" \
            --title "5.10" \
            --notes-file "release.md" \
            release_files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Send notification to TG (Safe)
        run: |
            MESSAGE="📦 Build completed! [Click](https://github.com/${{ env.RELEASE_REPO }}/releases/tag/${{ env.RELEASE_TAG }})"
            source functions.sh
            send_msg "$MESSAGE"
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
